// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_packet_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_packet_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "action.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packet_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_packet_2eproto;
namespace protobuf {
class whiteboardPacket;
struct whiteboardPacketDefaultTypeInternal;
extern whiteboardPacketDefaultTypeInternal _whiteboardPacket_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class whiteboardPacket final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protobuf.whiteboardPacket) */ {
 public:
  inline whiteboardPacket() : whiteboardPacket(nullptr) {}
  ~whiteboardPacket() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR whiteboardPacket(::google::protobuf::internal::ConstantInitialized);

  inline whiteboardPacket(const whiteboardPacket& from)
      : whiteboardPacket(nullptr, from) {}
  whiteboardPacket(whiteboardPacket&& from) noexcept
    : whiteboardPacket() {
    *this = ::std::move(from);
  }

  inline whiteboardPacket& operator=(const whiteboardPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline whiteboardPacket& operator=(whiteboardPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const whiteboardPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const whiteboardPacket* internal_default_instance() {
    return reinterpret_cast<const whiteboardPacket*>(
               &_whiteboardPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(whiteboardPacket& a, whiteboardPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(whiteboardPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(whiteboardPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  whiteboardPacket* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<whiteboardPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const whiteboardPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const whiteboardPacket& from) {
    whiteboardPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(whiteboardPacket* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.whiteboardPacket";
  }
  protected:
  explicit whiteboardPacket(::google::protobuf::Arena* arena);
  whiteboardPacket(::google::protobuf::Arena* arena, const whiteboardPacket& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionFieldNumber = 4,
    kVersionFieldNumber = 1,
    kPacketTypeFieldNumber = 2,
    kPacketIdFieldNumber = 3,
  };
  // .protobuf.PacketAction action = 4;
  bool has_action() const;
  void clear_action() ;
  const ::protobuf::PacketAction& action() const;
  PROTOBUF_NODISCARD ::protobuf::PacketAction* release_action();
  ::protobuf::PacketAction* mutable_action();
  void set_allocated_action(::protobuf::PacketAction* value);
  void unsafe_arena_set_allocated_action(::protobuf::PacketAction* value);
  ::protobuf::PacketAction* unsafe_arena_release_action();

  private:
  const ::protobuf::PacketAction& _internal_action() const;
  ::protobuf::PacketAction* _internal_mutable_action();

  public:
  // uint32 version = 1;
  void clear_version() ;
  ::uint32_t version() const;
  void set_version(::uint32_t value);

  private:
  ::uint32_t _internal_version() const;
  void _internal_set_version(::uint32_t value);

  public:
  // uint32 packet_type = 2;
  void clear_packet_type() ;
  ::uint32_t packet_type() const;
  void set_packet_type(::uint32_t value);

  private:
  ::uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(::uint32_t value);

  public:
  // uint32 packet_id = 3;
  void clear_packet_id() ;
  ::uint32_t packet_id() const;
  void set_packet_id(::uint32_t value);

  private:
  ::uint32_t _internal_packet_id() const;
  void _internal_set_packet_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.whiteboardPacket)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::protobuf::PacketAction* action_;
    ::uint32_t version_;
    ::uint32_t packet_type_;
    ::uint32_t packet_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// whiteboardPacket

// uint32 version = 1;
inline void whiteboardPacket::clear_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.version_ = 0u;
}
inline ::uint32_t whiteboardPacket::version() const {
  // @@protoc_insertion_point(field_get:protobuf.whiteboardPacket.version)
  return _internal_version();
}
inline void whiteboardPacket::set_version(::uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:protobuf.whiteboardPacket.version)
}
inline ::uint32_t whiteboardPacket::_internal_version() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.version_;
}
inline void whiteboardPacket::_internal_set_version(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.version_ = value;
}

// uint32 packet_type = 2;
inline void whiteboardPacket::clear_packet_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.packet_type_ = 0u;
}
inline ::uint32_t whiteboardPacket::packet_type() const {
  // @@protoc_insertion_point(field_get:protobuf.whiteboardPacket.packet_type)
  return _internal_packet_type();
}
inline void whiteboardPacket::set_packet_type(::uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:protobuf.whiteboardPacket.packet_type)
}
inline ::uint32_t whiteboardPacket::_internal_packet_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.packet_type_;
}
inline void whiteboardPacket::_internal_set_packet_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.packet_type_ = value;
}

// uint32 packet_id = 3;
inline void whiteboardPacket::clear_packet_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.packet_id_ = 0u;
}
inline ::uint32_t whiteboardPacket::packet_id() const {
  // @@protoc_insertion_point(field_get:protobuf.whiteboardPacket.packet_id)
  return _internal_packet_id();
}
inline void whiteboardPacket::set_packet_id(::uint32_t value) {
  _internal_set_packet_id(value);
  // @@protoc_insertion_point(field_set:protobuf.whiteboardPacket.packet_id)
}
inline ::uint32_t whiteboardPacket::_internal_packet_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.packet_id_;
}
inline void whiteboardPacket::_internal_set_packet_id(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.packet_id_ = value;
}

// .protobuf.PacketAction action = 4;
inline bool whiteboardPacket::has_action() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.action_ != nullptr);
  return value;
}
inline const ::protobuf::PacketAction& whiteboardPacket::_internal_action() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::protobuf::PacketAction* p = _impl_.action_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::PacketAction&>(::protobuf::_PacketAction_default_instance_);
}
inline const ::protobuf::PacketAction& whiteboardPacket::action() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.whiteboardPacket.action)
  return _internal_action();
}
inline void whiteboardPacket::unsafe_arena_set_allocated_action(::protobuf::PacketAction* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.action_);
  }
  _impl_.action_ = reinterpret_cast<::protobuf::PacketAction*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.whiteboardPacket.action)
}
inline ::protobuf::PacketAction* whiteboardPacket::release_action() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::PacketAction* released = _impl_.action_;
  _impl_.action_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::protobuf::PacketAction* whiteboardPacket::unsafe_arena_release_action() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:protobuf.whiteboardPacket.action)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::PacketAction* temp = _impl_.action_;
  _impl_.action_ = nullptr;
  return temp;
}
inline ::protobuf::PacketAction* whiteboardPacket::_internal_mutable_action() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.action_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::PacketAction>(GetArena());
    _impl_.action_ = reinterpret_cast<::protobuf::PacketAction*>(p);
  }
  return _impl_.action_;
}
inline ::protobuf::PacketAction* whiteboardPacket::mutable_action() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::protobuf::PacketAction* _msg = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:protobuf.whiteboardPacket.action)
  return _msg;
}
inline void whiteboardPacket::set_allocated_action(::protobuf::PacketAction* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.action_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.action_ = reinterpret_cast<::protobuf::PacketAction*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.whiteboardPacket.action)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_packet_2eproto_2epb_2eh
